### ISSUE TITLE
Add configuration to disable excreta and grass gen (other mods might do this)

### ISSUE THREAD

**Issue by dizzyboy92** [a3626a/HungryAnimals#11]

**Comment by a3626a** [comment]
Actually you can do this. However, possibly annoying to do. I will consider adding one-line config for this.

1. Excreta

`config/hungryanimals/attributes/*.json`

`"hungryanimals.excretion_factor" : 0.0`

2. Grass gen

`config/hungryanimals/world.json`

`grass_probability  : 0.0`

**Comment by a3626a** [comment]
If you have more questions, feel free to leave issue.
