### ISSUE TITLE
NoClassDefFoundError on server

### ISSUE THREAD

**Issue by tyra314** [a3626a/HungryAnimals#12]
When running Hungry Animals on my server I get the following crash during startup:

https://gist.github.com/tyra314/de2b752ee23d70a14d69df2b313e7ff8

I'm running:
- Minecraft 1.12.2
- Forge 14.23.1.2582
- HungryAnimals: 1.12.2-5.1.0.3

**Comment by a3626a** [comment]
Fixed 5.1.0.4
