### ISSUE TITLE
Disconnect from server

### ISSUE THREAD

**Issue by tyra314** [a3626a/HungryAnimals#13]
When encountering an animal, I get disconnected from the server.

The server log just contains:

> [14:20:54] [Server thread/INFO]: tyra_oa lost connection: Disconnected
> [14:20:54] [Server thread/INFO]: tyra_oa left the game

The client log contains an uncaught error:
`io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Undefined message for discriminator 0 in channel Hungry Animals`

https://gist.github.com/tyra314/8b81778acd330f378aabce07fc02d393

I'm running:
-   Minecraft 1.12.2
-   Forge 14.23.1.2582
-   HungryAnimals: 1.12.2-5.1.1.0

**Comment by a3626a** [comment]
Thank you for your report
Try HungryAnimals: 1.12.2-5.1.1.1

**Comment by tyra314** [comment]
Seems fixed, thanks
