### ISSUE TITLE
Crash with NPE in spawnBaby()

### ISSUE THREAD

**Issue by tyra314** [a3626a/HungryAnimals#14]
I got the following single-player server crash:

> java.lang.NullPointerException: Ticking entity

Crash report:  https://gist.github.com/tyra314/af38bf785153884e634d9769d3860484

I'm running:
-   Minecraft 1.12.2
-   Forge 14.23.1.2582
-   HungryAnimals:  1.12.2-5.1.2.0

**Comment by a3626a** [comment]
Did you delete old config?

**Comment by tyra314** [comment]
I deleted the config and haven't seen the crash since. I close it for now.
