### ISSUE TITLE
Adding modded animals causes StackOverflow

### ISSUE THREAD

**Issue by Xechon** [a3626a/HungryAnimals#15]
[crash-2018-01-06_13.57.27-client.txt](https://github.com/a3626a/HungryAnimals/files/1609220/crash-2018-01-06_13.57.27-client.txt)

It seems the API registerAnimal() function calls itself in its argument with no escape clause or logic.

**Comment by a3626a** [comment]
It is fixed after : https://minecraft.curseforge.com/projects/hungryanimals/files/2517261
