### ISSUE TITLE
Wolves no longer attack skeletons

### ISSUE THREAD

**Issue by CatastropheBlack** [a3626a/HungryAnimals#24]
Not necessarily a bug, and could be easily re-added via config, but I was not expecting this change.  Perhaps re-add skelly hunting to default hungry wolf behavior?  Wolves could also eat bones, just to give them a reason to hunt skellies, but that might be annoying when trying to get bones/bonemeal in early game.

**Comment by a3626a** [comment]
I will take a look within a day.

**Comment by a3626a** [comment]
fixed by 6debb96

**Comment by a3626a** [comment]
It was a bug, it have been removing all vanilla targeting AIs.

**Comment by a3626a** [comment]
https://minecraft.curseforge.com/projects/hungryanimals/files/2537650
