### ISSUE TITLE
Crash with Wolf Armor and Storage mod

### ISSUE THREAD

**Issue by CobaltRealm** [a3626a/HungryAnimals#27]
https://pastebin.com/cZ4qVacV

**Comment by a3626a** [comment]
For workaround,
you can disable "Model Growing" option for wolves.

**Comment by CobaltRealm** [comment]
Thanks!

**Comment by a3626a** [comment]
Fixed. You can enable Model Growing for wolf.
5083ca2d9e6311a975503f84e75caf79e1d18caf
