### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [a3626a/HungryAnimals#40]
Hello again!

There seems to be an issue with the latest version:

- https://paste.ee/p/0xeIf

* Just wanted to mention that I’m also using the latest version of Forge

**Comment by a3626a** [comment]
Hungry Mechanics needs updates.

**Comment by a3626a** [comment]
https://minecraft.curseforge.com/projects/hungryanimals/files
https://minecraft.curseforge.com/projects/hungry-mechanics/files
