### ISSUE TITLE
The game crashes when opening or creating a world

### ISSUE THREAD

**Issue by ZapikCZ** [a3626a/HungryAnimals#41]
Forge version: forge-14.23.4.2713
Hungry Animals version: hungryanimals-1.12.2-5.4.5.0 (Beta)
   with both the hungryanimals or hungryanimals-example config
Hungry Mechanics version: hungrymechanics-1.12.2-5.3.0.1 (Beta)
   with the vanilla config
Using the Twitch Launcher

Crash report: https://pastebin.com/GwAmN4uz

The LootTweaker mod hasn't been configured, removing it doesn't solve the proble either.

**Comment by a3626a** [comment]
Hungry Mechanics needs updated. I am working on it.

**Comment by a3626a** [comment]
https://minecraft.curseforge.com/projects/hungryanimals/files
https://minecraft.curseforge.com/projects/hungry-mechanics/files

**Comment by ZapikCZ** [comment]
That crash has been fixed, but the game still crashes when the world isn't a superflat one.

Pastebin of the new crashlog: https://pastebin.com/ZzfsQb7x

Hungry Animals and Hungry Mechanics: 5.4.0.0

**Comment by wenlfs** [comment]
I'm having the same crash when creating a new world, but it only happen when using other mods. I'm able to play with only Hungry animals and once happened that it didn't crash when using other mods. I'm using the default config

Log: https://pastebin.com/8x7xw6iX

Hungry Animals: 1.12.2-5.4.6
Forge: 14.23.4.2759

**Comment by LemADEC** [comment]
Any chance we get a fix for this?

**Comment by oortcloud1996** [comment]
Ok i will try it on this weekend.

**Comment by a3626a** [comment]
@LemADEC 
Can you post crash logs?

**Comment by LemADEC** [comment]
I was just evaluating the mod for a new modpack, since that issue is a show stopper, I didn't even try to load the mod.

**Comment by Rimevel** [comment]
Also got problems with creating a world.
https://paste.dimdev.org/atapaverah.mccrash

**Comment by a3626a** [comment]
It is a conflict with BetterWithMods. Thanks to @Rimevel and @wenlfs .

Turning off llama drop tweak of BetterWithMods will fix it.
(I will also update HungryAnimals not to crash, just to print warning messages for this.)
