### ISSUE TITLE
Incompatibility with DynamicTrees

### ISSUE THREAD

**Issue by Valiant70** [a3626a/HungryAnimals#45]
This never happened before I installed HungryAnimals, and never happened again after I removed HungryAnimals. I don't understand why, but HungryAnimals breaks DynamicTrees.

I strongly suggest removing as much coremod stuff as possible from HungryAnimals as you seem to have rampant incompatibility issues with many other mods.

[crash-2019-08-25_17.34.40-client.txt](https://github.com/a3626a/HungryAnimals/files/3538822/crash-2019-08-25_17.34.40-client.txt)
[crash-2019-08-25_17.39.56-client.txt](https://github.com/a3626a/HungryAnimals/files/3538823/crash-2019-08-25_17.39.56-client.txt)

**Comment by a3626a** [comment]
I commented here https://github.com/ferreusveritas/DynamicTrees/issues/309.
