### ISSUE TITLE
Vanilla Horses aren't working properly

### ISSUE THREAD

**Issue by PitchBright** [a3626a/HungryAnimals#6]
There are a few issues with the Vanilla Horses.

1) You can't click on them with a debug glass
2) They don't show their stats in the small GUI
3) They don't drop the correct stuff

It's entirely possible that their Hunger, Poop, and Grazing doesn't work either, but I can't confirm that with the first two problems, making it impossible to check their values.

**Comment by a3626a** [comment]
Sorry for REALLY late reply.
Simple Answer : Hungry Animals didn't support horses.

But now it does.
https://minecraft.curseforge.com/projects/hungryanimals/files/2512992
