### ISSUE TITLE
Trying to add modded animals

### ISSUE THREAD

**Issue by Omuck3** [a3626a/HungryAnimals#9]
Hello.  I am trying to add Hungry Animals support to some of the animals in LotsOMobs.  However, they just seem to run around and never eat.  Here is my code for a goat(some taken from the default cow code):
`goat {
        D:"Abiltiy: Max health of the animal"=20.0
        D:"Abiltiy: Movement speed of the animal"=0.2
        I:"Abiltiy: max hunger"=200
        I:"Abiltiy: needed amount of hunger consumption to produce a pile of excreta"=50
        D:"Behavior: needed ratio(hunger/maxhunger) to do the courting"=0.8
        D:"Behavior: probability to do the courting per a tick"=0.0025
        I:"Behavior: ticks needed to produce a bucket of milk"=6000
        S:"HungerAcquisition: byBlock Rate" <
            (minecraft:tallgrass)=(15.0)
            (minecraft:wheat,7)=(50.0)
         >
        S:"HungerAcquisition: byFood Rate" <
            (minecraft:wheat)=(50.0)
            (minecraft:reeds)=(20.0)
         >
        D:"HungerUsage: basic rate"=0.005
        D:"HungerUsage: to do the courting"=5.0
        D:"HungerUsage: to make a child"=25.0
    }
`

Am I doing something wrong, by chance?

Thanks!

**Comment by a3626a** [comment]
sorry.
this configuration system is completely changed and i will not cover 1.7.10 now.
